name: LifeSteal
version: '1.9.3'
main: eu.vibemc.lifesteal.Main
api-version: 1.18
authors: [ devPrzemuS ]
description: Plugin for stealing lives, the grim reaper has arived....
softdepend:
  - PlaceholderAPI